#!/bin/bash
set -e

#-----------------
# migrate
#
sozo migrate

#-----------------
# auth write
#
scripts/default_auth.sh

#-----------------
# client setup
#
export WORLD_ADDRESS="0x3cc6a9ed7c1e2485d4fe787a7191f1f6835cd905a3d0731fc9e24f5a39d9415"
export RPC_URL="http://localhost:5050/"

cp target/dev/manifest.json ../client/src/
cd ../client
npm run create-components $RPC_URL $WORLD_ADDRESS

#-----------------
echo "--- DONE! 👍"
