#!/bin/bash
set -e

export WORLD_ADDRESS="0x592275900516a2e313cb6a85324566c9f4265b21f5a0afa5adaf890d2d9ea0e"
export RPC_URL="http://localhost:5050/"

#sozo --offline build
sozo migrate

scripts/default_auth.sh

cp target/dev/manifest.json ../client/src/

cd ../client
yarn run codegen
yarn run create-components $RPC_URL $WORLD_ADDRESS

echo "--- DONE!"
