#!/bin/bash
set -e

export WORLD_ADDRESS="0x76724b8917bd87868d80ae286a71ba7008a0d1a02381bc483fcfbe61d9b3ee0"
export RPC_URL="http://localhost:5050/"

#sozo --offline build
sozo migrate

scripts/default_auth.sh

cp target/dev/manifest.json ../client/src/

cd ../client
yarn run codegen
yarn run create-components $RPC_URL $WORLD_ADDRESS

echo "--- DONE!"
